### ISSUE TITLE
plan a route with new profil

### ISSUE THREAD

**Issue by fixifoxy** [OsmAnd-Rendering/Motorcycle#11]
Bonjour Christoph,
c est Horst d Autriche..
avec les nouveaux profils je recommence mes etudes  concernant
Plan a route
1. avec Map Markers
2. Plan a Route
   ---open existing tracks.
Au debut je n avais pas remarke que j utilisais un ancien profil s appellant "CycloRoute" et je ne sais plus ou je l avais telecharge.
1.Donc je partais avec 2 Map Markers (Depart et arrivee( Markers.gpx)
2.click More. 
3.Plan a route. And Hubertusalm mit unpaved roads.gpx etait fait.
j etais surpris parce que un chemin avec beaucoup de trafic  etait propose.
Normalement je choisis "Show on Map" et je pars on route.
Mais cette fois-ci j ai choisi "Navigation"
et maintenant il change le route. c est que j ai recorded.
"with Navigation and recordedandsaved.gpx"
Et c est le chemin que j avais attendu.
je vais faire ces tests avec gros_trail et petit_trail.

 
[Plan a Route.zip](https://github.com/OsmAnd-Rendering/Motorcycle/files/12070609/Plan.a.Route.zip)

**Comment by cricri-du-lauragais** [comment]
I find differences between a route calculated on the windows computer and on my phone.
I think it's because of this parameter (line 3 of the xml file)
	<attribute name="heuristicCoefficient" value="3.4"/>
but when it's deleted or set to "1" the calculation is very very slow and often impossible.
this is the price to pay for a fast calculation.
there are also minimal differences when the direction is reversed on the same phone.
my tests have shown that, even if there are occasional differences, overall, the choice of paths is consistent.

**Comment by fixifoxy** [comment]
please delete
